/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubmissionId = IDL.Nat;
export const Time = IDL.Int;
export const Submission = IDL.Record({
  'id' : SubmissionId,
  'fullName' : IDL.Text,
  'businessEmail' : IDL.Text,
  'website' : IDL.Text,
  'company' : IDL.Text,
  'monthlyAdSpend' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'biggestProblem' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getSubmission' : IDL.Func([SubmissionId], [Submission], ['query']),
  'submitAuditForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [SubmissionId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubmissionId = IDL.Nat;
  const Time = IDL.Int;
  const Submission = IDL.Record({
    'id' : SubmissionId,
    'fullName' : IDL.Text,
    'businessEmail' : IDL.Text,
    'website' : IDL.Text,
    'company' : IDL.Text,
    'monthlyAdSpend' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'biggestProblem' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getSubmission' : IDL.Func([SubmissionId], [Submission], ['query']),
    'submitAuditForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [SubmissionId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };